[[ZeroMQ]]
arch = "aarch64"
git-tree-sha1 = "f46814a06fbad2c44a6272958762dbee21221e70"
os = "macos"

    [[ZeroMQ.download]]
    sha256 = "7a0f7bea7c25fa3f00dea3f30e84d5a7e8ac46553863f74ef31e36bd04f8659e"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.aarch64-apple-darwin.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52db857dd0a488e3886bad2ba792855e5f5bd7de"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "f9fc425bd8e7a0a186827c940f242649b992710e839b9eec075d50a3c3484c32"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.aarch64-linux-gnu-cxx03.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "485efb2ae0ac0c0b6a6f2f865ba145638f14c607"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "e4f356a213a404e9bba27479261b503d46a84e918300138f5aa881a2c6fbfcb5"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.aarch64-linux-gnu-cxx11.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3a24458f7b6ca91e35b38eb96e2dfa4f445769a3"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "74f6c201e3f2fa49c848e91d4104489344f12cb3a21b89085e435202a136368b"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.aarch64-linux-musl-cxx03.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6426be39247371ade56eacc3d049d2522f2f9aba"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "128dbe47b1094e21995c9a6c407d5490116fea7d39e06104b36e1695974e460e"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.aarch64-linux-musl-cxx11.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
git-tree-sha1 = "0dc48af0340efcd46f3dc40fe5ce116afe201afe"
os = "freebsd"

    [[ZeroMQ.download]]
    sha256 = "42a0831b85d4e9c4741cf636cba3fe2cafb1a474cec837eba223de5ead27685b"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.aarch64-unknown-freebsd.tar.gz"
[[ZeroMQ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38108719b632fdc4f6c99975f0894967b4c29cc9"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "7d2569fe6f523bfcb065f0105b741cc81cde1b6a4617c571ba227d45970c2d7b"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ZeroMQ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb8896935cf8a5fdbf70508ba9bc391054d64ea3"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "117ddd81dc27af0113d959be3db055140432f7aa85cfc185dc1b17f3f1e7c549"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ZeroMQ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a92ebcedac6405273bb748d7ee1f66883cb6bb35"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "d6370fd918c56d84017f9c2fee29ed409f52086f7cde9a971061fcc5c1262b47"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ZeroMQ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80508a36d04c567954bc7e78ba863e6773d9aee9"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "198b4d598fc628159ab0c4d7ca2e31743e1a422d3583d75e26271322a1fca412"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ZeroMQ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4d16a030351c63b82ba076339add546c7e6fd00"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "8822bf2b97cc1e80194b33822d5569e8ae1010f8a72abdb4566320d9266344dc"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ZeroMQ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b126274089d68e0da2ffac86207a345dc59d9f3"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "c056a2f4f6dee6558f57bdf460960ba7ca08c57275177386af488b627e090855"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ZeroMQ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9982d03e4b043c58ea10ec8fe3022c818d3ebdec"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "fb547991eae6bf225c4daf1153232cc1c634f80182db42e957711a1fae249966"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ZeroMQ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2deb62f138e4736b2979f42372c17abf397958a6"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "f8879956c5198bdb2f01f7f36a8734f3876830a339ab330edd4955cfd0ca3592"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02de238fedf71386bca5cf60cd581addd87149cc"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "18b67ef638e4bf284bb8142f91da02c45c4a53ed86696848ad51f322a1dedae6"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.i686-linux-gnu-cxx03.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3cff96ac8af98f3a235bbb8ac111dbb9690a4de"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "e4ec344b5d305f2ba27a10f0a0f82954277c31d1821b089c3aad57064cecb780"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.i686-linux-gnu-cxx11.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0db56dee3103e5dde1bc30ef7fdce24dc3f99ea3"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "434b5d88f3f1ffa86180bca286fce0b181efb103c83c341159198875c407d8b8"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.i686-linux-musl-cxx03.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ad068631e480b1a8e309a3b5058c0bb41dd7dfa"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "e7ce390b9fc201d1e7692c269f974c292904c7d30ffbb698036a884f2a2946f6"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.i686-linux-musl-cxx11.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc2a0f2e15dbf0c2d1232e273b6e690c800005db"
os = "windows"

    [[ZeroMQ.download]]
    sha256 = "e129815e0620a9931a4247a99f2d851abbf076c5771cb1742d22638266c9cf30"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.i686-w64-mingw32-cxx03.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6223197bb4a85b544162e5cb739697b20901cb65"
os = "windows"

    [[ZeroMQ.download]]
    sha256 = "0e0e525a8390a6cc8587ab81bae2ea1aeb4d195fac46a72e844b80ddc5984f71"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.i686-w64-mingw32-cxx11.tar.gz"
[[ZeroMQ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58dd7993c0542b7bf550adb01b0c53067914eeca"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "fd7ab434ed73935252ab371dc8953f554cf12f8b1eb482c40e2dbd28f69ae978"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ZeroMQ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6e838ca519bae04854295f8842fef3e567ed89f"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "422c3b0c8518b67d063415b386ffc1ade264dada5aa73b92ba75581f71697799"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ZeroMQ]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "35c24b2c9b4665aa895384d6ddfd10540a24a0e3"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "ca1c741218a8ec298607368dc6b9ff3a3d3767ef9be01f3620c3cf1dd7279757"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.riscv64-linux-gnu-cxx03.tar.gz"
[[ZeroMQ]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6b0ff5cd190616cbf1cc8262f45ac31f209b8d2"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "d8c037e39106b53ac7d7a3db1e490fca618069ed949241fd6ab5b525fe2fd13e"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.riscv64-linux-gnu-cxx11.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
git-tree-sha1 = "468fc7a0b8f6396bae8d8491a961c2539b94d70e"
os = "macos"

    [[ZeroMQ.download]]
    sha256 = "7ceca2cf6394d6ed85ec5d938ae1beb029c22a117bbf4150ea70d174dd48e768"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.x86_64-apple-darwin.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ffcd46b8b990de13255407d76a8033ac2509369"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "e12d79ea89b905641b69562239c5f20c937d12674ccfc5c56619b077fb9a7cc1"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.x86_64-linux-gnu-cxx03.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bc7c9c88c2cc8ab97eaf7695cf67f0ef60f1e5c"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "9169fe0aa8e449d2c8e9599f69b2e696ceb6ac2db25ee2e0e0b3ed2de316671d"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.x86_64-linux-gnu-cxx11.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "607fd6f761cd8df058fae3f0d4912e685e4c126e"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "93d385eb38403506f5f0dcea24b98352a868fa152a58925445261f7c9d4b8b96"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.x86_64-linux-musl-cxx03.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e081670c2a87e897483b04b0a24d8503f69d63a0"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "0f9dbe9c5329ca3e13c5623194bf422ce5185075ea4f4d1e4eec3fafbb466194"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.x86_64-linux-musl-cxx11.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
git-tree-sha1 = "b0a226120aee1e8d95faabc34df7521a6d1d8828"
os = "freebsd"

    [[ZeroMQ.download]]
    sha256 = "c6be38d577d7c7404966cea3f1cac2dbc6bb598342535b26f793ee18a899e00c"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.x86_64-unknown-freebsd.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2887e2fd53d3101c23f7582b5dee3b8406bf55c3"
os = "windows"

    [[ZeroMQ.download]]
    sha256 = "941047ee7736b628f5a82f407a72c31ddd5ae24cc32d6fd509284143d944a6eb"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60be90c4216ce335babb3c54aba7e0df316e9450"
os = "windows"

    [[ZeroMQ.download]]
    sha256 = "4f151f5cfe1c356c3e5349b8e4d79c4f40b14d14cde091d311f988403bf65e49"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+2/ZeroMQ.v4.3.5.x86_64-w64-mingw32-cxx11.tar.gz"
