[[ZeroMQ]]
arch = "aarch64"
git-tree-sha1 = "a766b336de5b81b9958236a3ee35f8673b4048df"
os = "macos"

    [[ZeroMQ.download]]
    sha256 = "a97ba8b823e25954512d9f145fe2584fdc87721de0cfb204b4fdcc724d8bb20d"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.aarch64-apple-darwin.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "63585736b40cb7a7709cf897b0ef5ce1f7fe7581"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "cd089b5c795d8a3f18e5a75071c1676691adf40c01d2c6d2da022404d718964e"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.aarch64-linux-gnu-cxx03.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b71f976b36e0c93b1b2f38d58d9adcd9fb16b2e"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "7ec249ba35f2fda905c35d6e7204295e04d7017fb6f966b4af51fe76555c8bee"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.aarch64-linux-gnu-cxx11.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4591bbb7be0f56fa5d9041cf7a65856d87c49662"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "6724fcc9032033f03bd30636e1daf0e0a3b31b1a9a100cda64b514b50c8bbdde"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.aarch64-linux-musl-cxx03.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f54592fda39f2de1c4216a2d1c736d03156d6081"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "530ec5fe38fb3525e225ff24d90df3f741d5c4587840cca75de7c23ba0b090ee"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.aarch64-linux-musl-cxx11.tar.gz"
[[ZeroMQ]]
arch = "aarch64"
git-tree-sha1 = "f373484ec5d5e78027209b2b29fdc7c93cbb9c1f"
os = "freebsd"

    [[ZeroMQ.download]]
    sha256 = "10e369b1be77a7611a45903b7b098dc3b3c3d3c118613c245696bee4980ae650"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.aarch64-unknown-freebsd.tar.gz"
[[ZeroMQ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f1c8cc5ea414edd249771ab5cecf36effb9a500"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "4e03c0a89c8b3cd5ea1763dfd22a7766192ab81472b2e72a9e42136e541aaf4d"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ZeroMQ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f67eaac16c4516c6c8fd768286c55a0884cb0859"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "90657e6f16566960549a2916967f6ef947c7044636978365366d2e55224fa6c6"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ZeroMQ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e31e5e2f085b60b3a9b7f92409f017ea518129c"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "f2592779d7e8ea05fa228193e0f2cfc3240211bfb57f0fe3cc17622c9d0021e0"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ZeroMQ]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0bc413a57b55f97138510c8d49ccaffd3169f3d"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "9f77106db1a7bcdc80eb13268022624553f8ba8d54b325c3e99590d623e75ee9"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ZeroMQ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce8da93e765e175727cc91cb13ecfb308c08800d"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "2b5c088022ff31ee7dd2f2311bf9a7eed7b0c3ddf25f3cefa0797f039428f5d1"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ZeroMQ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09ddfe4a1084ec97705d5d840660a4ad02db27e3"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "f47fa576c4a7ed1823c5ec1385f79009dbe640683bdd1c300a492d8246f7b477"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ZeroMQ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f30dc2d50d743478e979b560b55aa21d9de7930e"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "b76fcd16a757befb2bc48ccfebaa003f53f6b2717434c01a5fe7cc6f585d24c2"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ZeroMQ]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c9dba3fddb71aaa0f94ea60f1f5a2a49099c3c6"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "ed34716e16e4a6ff6ef36f32f69286d54cd16db5045c134db60425a2cca4bac1"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e046d0304bdf20846353ac370809501169b95899"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "70e50d93dd656900f47b396d4bd579a8c1129bb2b53e2a715a58670808e5cde9"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.i686-linux-gnu-cxx03.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0558d0ec480c37d652da5da406221164ce9e3a26"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "ae0af56ba9623c42052281f66b0114561c7c10fa393c2dd2d5158ea9588bb595"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.i686-linux-gnu-cxx11.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed075bb2e47fd8381d574130810a9dc59999b425"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "94f4994b60ee2a2de4309bf62831f5f27b3a1ddc795f157fc66bc9ffb8a7271e"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.i686-linux-musl-cxx03.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "843b144838ed0916c003e8497469902d965fffc5"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "e3b24957b3801401747470a4eb4a8d6e19d23cd48c4a4bc33a437bbb01989f87"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.i686-linux-musl-cxx11.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43ade9a2eb9dafb3b84ceb31fd64876f509bc228"
os = "windows"

    [[ZeroMQ.download]]
    sha256 = "74e5b268156418f2c71b29b51b9cd6a71ab85b48bf715dbe85c96ecccf170c58"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.i686-w64-mingw32-cxx03.tar.gz"
[[ZeroMQ]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6a0fa1065be04c82e01cb3cd7d6d6970ceca36e"
os = "windows"

    [[ZeroMQ.download]]
    sha256 = "56c91e52c2ddd981a94ae2aa0d0310559b3e1adc624029090a2cfea1c696182c"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.i686-w64-mingw32-cxx11.tar.gz"
[[ZeroMQ]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "295d2826af34058297af9f372c38a913a2d1a8af"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "04c6b3e9587c5cde7431fdbfce9009016ddc0dc1090c0c85e3e9b73742edd3bd"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ZeroMQ]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55bc483893bc917a0a260e8470b4ea057b7811c7"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "9b2cb32724b7bff03b6ebe90ed150a99664f74572d7ff06cc50b3ddb532e0280"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
git-tree-sha1 = "afb29765cf58e55871759a185140776b3ab280d2"
os = "macos"

    [[ZeroMQ.download]]
    sha256 = "189fe3897da4181bc321da8d632d34f430069fd42a8eddcbefe3fa96134f36e0"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.x86_64-apple-darwin.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5bf9684c3ee0e05beb4ed886f45af853ad964f5"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "be504c733393e9973905e8be94c3210d3ad80aad2cac1efd2d9c380b588fe475"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.x86_64-linux-gnu-cxx03.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4c570c600644e713bebf907a2dc9004eae04ccb"
libc = "glibc"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "ae556caa4502e8b89697ce5b62698700ab55bd668102d38a25bd7ba5e81e7f38"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.x86_64-linux-gnu-cxx11.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61063ecc33935dbb725abc7a182777aad8a6f7b5"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "3cbad521151ff3690fcebf76ec94ea836fd1e9a6c2cb49c6e4ddd3a4af57c28a"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.x86_64-linux-musl-cxx03.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2d46bd30bb65d8b228440f43c8e0172342086d2"
libc = "musl"
os = "linux"

    [[ZeroMQ.download]]
    sha256 = "6e97ab7fc6a3a19fc052eaab3a8021185d4b969ea6b81d02a8167d73fabe1773"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.x86_64-linux-musl-cxx11.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
git-tree-sha1 = "77aeb2bb7fa6d77cdef5c00d69092a866f749edd"
os = "freebsd"

    [[ZeroMQ.download]]
    sha256 = "679eb907aa5172b8203044b7cf6a2484420ccd2e45c71a23de84a6e33a196287"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.x86_64-unknown-freebsd.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5625ffb6b9e81abe14a00ba258d11b8f8d38703"
os = "windows"

    [[ZeroMQ.download]]
    sha256 = "6edd279c5ee49f82afc9f46df443aec8eddb560b1868fef6ca1d5bfaaeccdc4b"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[ZeroMQ]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad4868e3f1b2dbb64e130e14968992bd855b85d6"
os = "windows"

    [[ZeroMQ.download]]
    sha256 = "dbb6cd42be2ce327fc68d683d9fd1a47d334a885a8c6ddbd34e952bc6609e034"
    url = "https://github.com/JuliaBinaryWrappers/ZeroMQ_jll.jl/releases/download/ZeroMQ-v4.3.5+1/ZeroMQ.v4.3.5.x86_64-w64-mingw32-cxx11.tar.gz"
